// examples/vue/src/App.vue
<script setup lang="ts">
import { onUnmounted, ref } from "vue";
import {
  createDocLayout,
  DocLayoutError,
  type DocLayoutDetector,
  type DocLayoutResult
} from "web-sdk-pp-doclayoutv3";

const detector = ref<DocLayoutDetector>();
const file = ref<File>();
const status = ref("请选择图片");
const progress = ref(0);
const result = ref<DocLayoutResult>();
const error = ref<{ code?: string; message: string }>();

onUnmounted(() => {
  void detector.value?.dispose();
});

function selectImage(event: Event): void {
  file.value = (event.target as HTMLInputElement).files?.[0];
}
async function detect(): Promise<void> {
  if (file.value === undefined) return;
  error.value = undefined;
  try {
    await detector.value?.dispose();
    detector.value = await createDocLayout({
      onProgress: (event) => {
        status.value = `${event.phase}: ${event.status}`;
        if (event.totalBytes !== undefined)
          progress.value = ((event.loadedBytes ?? 0) / event.totalBytes) * 100;
      }
    });
    result.value = await detector.value.detect(file.value, { threshold: 0.5 });
    progress.value = 100;
    status.value = "检测完成";
  } catch (caught) {
    error.value =
      caught instanceof DocLayoutError
        ? { code: caught.code, message: caught.message }
        : { message: String(caught) };
  }
}
</script>

<template>
  <main>
    <h1>Vue 示例</h1>
    <input type="file" accept="image/*" @change="selectImage" /><button @click="detect">
      检测
    </button>
    <p>{{ status }}</p>
    <progress max="100" :value="progress" />
    <pre>{{ JSON.stringify(error ?? result, null, 2) }}</pre>
  </main>
</template>

// examples/react/src/App.tsx
import { useEffect, useRef, useState, type ChangeEvent, type ReactElement } from "react";
import {
  createDocLayout,
  DocLayoutError,
  type DocLayoutDetector,
  type DocLayoutResult
} from "web-sdk-pp-doclayoutv3";

export function App(): ReactElement {
  const detector = useRef<DocLayoutDetector | undefined>(undefined);
  const [file, setFile] = useState<File>();
  const [status, setStatus] = useState("请选择图片");
  const [progress, setProgress] = useState(0);
  const [result, setResult] = useState<DocLayoutResult>();
  const [error, setError] = useState<{ code?: string; message: string }>();

  useEffect(() => {
    return () => {
      void detector.current?.dispose();
    };
  }, []);

  const selectImage = (event: ChangeEvent<HTMLInputElement>): void =>
    setFile(event.target.files?.[0]);
  const detect = async (): Promise<void> => {
    if (file === undefined) return;
    setError(undefined);
    try {
      await detector.current?.dispose();
      detector.current = await createDocLayout({
        onProgress: (event) => {
          setStatus(`${event.phase}: ${event.status}`);
          if (event.totalBytes !== undefined)
            setProgress(((event.loadedBytes ?? 0) / event.totalBytes) * 100);
        }
      });
      setResult(await detector.current.detect(file, { threshold: 0.5 }));
      setProgress(100);
      setStatus("检测完成");
    } catch (caught) {
      setError(
        caught instanceof DocLayoutError
          ? { code: caught.code, message: caught.message }
          : { message: String(caught) }
      );
    }
  };

  return (
    <main>
      <h1>React 示例</h1>
      <input type="file" accept="image/*" onChange={selectImage} />
      <button onClick={() => void detect()}>检测</button>
      <p>{status}</p>
      <progress max="100" value={progress} />
      <pre>
        {error ? JSON.stringify(error, null, 2) : result ? JSON.stringify(result, null, 2) : ""}
      </pre>
    </main>
  );
}
